image: ruby:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  - bundle install
  - curl -o ../rclone.zip https://downloads.rclone.org/v1.57.0/rclone-v1.57.0-linux-amd64.zip
  - unzip ../rclone.zip -d ../
  - mv ../rclone-v1.57.0-linux-amd64/rclone ./
  - chmod 755 rclone

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - echo [=] Setting up rclone....
  - echo "$RCLONE_CONFIG_B64" | base64 -d > rclone.conf
  - echo [=] Syncing posts and assets....
  - ./rclone -v --config rclone.conf --include "*.md" --exclude "/assets/**" sync dropbox_blog_posts:/blog_posts ./_posts
  - ./rclone -v --config rclone.conf sync dropbox_blog_posts:/blog_posts/assets ./assets
  - rm -fr ./_posts/.git ./_posts/.zettel-notes
  - echo [=] Posts have been synced....
  - ls -a ./_posts
  - (cd _posts && for i in *' '*; do   mv "$i" `echo $i | sed -e 's/ /-/g'`; done)
  - echo [=] Building....
  - bundle exec jekyll build -d public
  - echo [=] Publishing....
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
