image: ruby:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  - bundle install
  - curl -o ../rclone.zip https://downloads.rclone.org/rclone-current-linux-amd64.zip
  - unzip ../rclone.zip
  - mv ../rclone/rclone ./
  - chmod 755 rclone

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - echo $RCLONE_CONFIG_B64 | base64 -d > rclone.conf
  - ./rclone --config rclone.conf sync dropbox_blog_posts:/blog_posts ./_posts
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
